version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 442042520759.dkr.ecr.us-east-1.amazonaws.com
  build:
    commands:
      - echo Building the Docker image...
      - docker build -t wild-rydes-app .
      - docker tag wild-rydes-app:latest 442042520759.dkr.ecr.us-east-1.amazonaws.com/wild-rydes-app:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 442042520759.dkr.ecr.us-east-1.amazonaws.com/wild-rydes-app:latest
      - echo Writing image definitions file...
      - printf '[{"name":"wild-rydes-app","imageUri":"442042520759.dkr.ecr.us-east-1.amazonaws.com/wild-rydes-app:latest"}]' > imagedefinitions.json
artifacts:
  files:
    - imagedefinitions.json
