name: Build and Deploy to ECR

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up AWS CLI and configure region
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: 
          aws-secret-access-key: 
          aws-region:   # Hardcoded region

      # Log in to Amazon ECR
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t wild-rydes-app .

      # Tag and Push Docker image to ECR
      - name: Tag and Push Docker image to ECR
        run: |
          IMAGE_URI="442042520759.dkr.ecr.us-east-1.amazonaws.com/wild-rydes-app"
          echo "Tagging image with: $IMAGE_URI"
          docker tag wild-rydes-app:latest $IMAGE_URI
          echo "Pushing image to ECR: $IMAGE_URI"
          docker push $IMAGE_URI
